fix(version): url error handler

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -94,11 +94,19 @@ bump-version:
         PATCH=$(echo "$LATEST_TAG" | awk -F '.' '{print $3}')
 
         # Get merge request for current commit hash
-        MERGE_REQUEST=$(curl --header "JOB-TOKEN: $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/repository/commits/${CI_COMMIT_SHA}/merge_requests")
+        MERGE_REQUEST=$(curl --header "JOB-TOKEN: $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/commits/${CI_COMMIT_SHA}/merge_requests")
 
         # If direct push to default branch
         if [ "$MERGE_REQUEST" = "[]" ]; then
           echo "[ERROR]: No Merge Request found for commit ${CI_COMMIT_SHA}!"
+          echo "[ERROR]: Halting Release!!!!"
+          exit 1
+        fi
+
+        API_ERROR=$(echo $MERGE_REQUEST | jq 'try .error')
+
+        if [ ! -z "$API_ERROR" ]; then
+          echo "[ERROR]: $API_ERROR!"
           echo "[ERROR]: Halting Release!!!!"
           exit 1
         fi
