fix(version): error refactor

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -96,23 +96,23 @@ bump-version:
         # Get merge request for current commit hash
         MERGE_REQUEST=$(curl --header "JOB-TOKEN: $CI_JOB_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/commits/${CI_COMMIT_SHA}/merge_requests")
 
+        API_ERROR=$(echo $MERGE_REQUEST | jq 'try .error')
+
+        # Check if the api access had errors
+        if [ ! -z "$API_ERROR" ]; then
+          echo "[ERROR]: $API_ERROR!"
+          echo "[ERROR]: Halting Release!!!!"
+          exit 1
+        fi
+
         # If direct push to default branch
         if [ "$MERGE_REQUEST" = "[]" ]; then
           echo "[ERROR]: No Merge Request found for commit ${CI_COMMIT_SHA}!"
           echo "[ERROR]: Halting Release!!!!"
           exit 1
         fi
-
-        API_ERROR=$(echo $MERGE_REQUEST | jq 'try .error')
-
-        if [ ! -z "$API_ERROR" ]; then
-          echo "[ERROR]: $API_ERROR!"
-          echo "[ERROR]: Halting Release!!!!"
-          exit 1
-        fi
         
-        
-        # Parse json for first (0th) merge request related to commit for labels and output 1 on finding the label
+        # Parse json for first (0th) merge request related to commit for labels and output true or false
         BUMP_MAJOR=$(echo $MERGE_REQUEST | jq '.[0].labels | any(index("bump-major"))')
         BUMP_MINOR=$(echo $MERGE_REQUEST | jq '.[0].labels | any(index("bump-minor"))')
 
@@ -131,7 +131,7 @@ bump-version:
         RELEASE_VERSION="${MAJOR}.${MINOR}.${PATCH}"
       fi
       echo "[INFO]: Versioning Completed...!"
-      echo "RELEASE_VERSION=${RELEASE_VERSION}"
+      echo "[INFO]: RELEASE_VERSION=${RELEASE_VERSION}"
       echo "RELEASE_VERSION=${RELEASE_VERSION}" >> release.env
   artifacts:
     untracked: false
